export const recipeList = [
	{
		id: "01",
		name: "Tartar de Atum",
		image: require("../../assets/images/tuna.png"),
		rating: "4.2",
		ingredients: ["Atum Fresco", "Suco de Limão", "Cebola Roxa", "Abacate"],
		time: "40 min",
		difficulty: "Médio",
		calories: "420 cal",
		color: "#006A4E",
		description:
			"Um prato delicioso e refrescante com atum fresco misturado com suco de limão e a crocância da cebola roxa e do abacate.",
		steps: [
			"Corte o atum fresco em cubos pequenos.",
			"Pique finamente a cebola roxa e o abacate.",
			"Misture o atum, a cebola roxa e o abacate em uma tigela.",
			"Regue com suco de limão e mexa delicadamente.",
			"Sirva gelado e aproveite!",
		],
	},
	{
		id: "02",
		name: "Lasanha",
		image: require("../../assets/images/lasgana.png"),
		rating: "3.6",
		ingredients: [
			"Massa de Lasanha",
			"Carne Moída",
			"Queijo Ricota",
			"Molho de Tomate",
		],
		time: "40 min",
		difficulty: "Médio",
		calories: "420 cal",
		color: "#f39c12",
		description:
			"Um clássico conforto italiano com camadas de massa de lasanha, carne moída saborosa, queijo ricota cremoso e molho de tomate ácido.",
		steps: [
			"Cozinhe a massa conforme as instruções da embalagem.",
			"Doure a carne moída em uma frigideira e tempere.",
			"Em um refratário, alterne camadas de massa, carne, ricota e molho.",
			"Repita as camadas e asse no forno até borbulhar e dourar.",
			"Deixe esfriar um pouco antes de servir.",
		],
	},
	{
		id: "03",
		name: "Cachorro-Quente",
		image: require("../../assets/images/hotdog.png"),
		rating: "4.6",
		ingredients: ["Pães de Hot Dog", "Salsichas", "Ketchup", "Mostarda"],
		time: "40 min",
		difficulty: "Médio",
		calories: "420 cal",
		color: "#FF0000",
		description:
			"Um clássico americano: pães recheados com salsichas suculentas, cobertos com ketchup e mostarda para um equilíbrio perfeito de sabores.",
		steps: [
			"Grelhe ou aqueça as salsichas até estarem bem cozidas.",
			"Coloque as salsichas nos pães.",
			"Adicione ketchup e mostarda por cima.",
			"Sirva com seus acompanhamentos favoritos e aproveite!",
		],
	},
	{
		id: "04",
		name: "Manchurian",
		image: require("../../assets/images/manchurian.png"),
		rating: "3.6",
		ingredients: ["Couve-Flor", "Molho de Soja", "Gengibre", "Alho"],
		time: "30 min",
		difficulty: "Fácil",
		calories: "350 cal",
		color: "#d35400",
		description:
			"Um prato indo-chinês popular com pedaços crocantes de couve-flor envoltos em um molho saboroso de soja, gengibre e alho.",
		steps: [
			"Corte a couve-flor em floretes e afervente.",
			"Prepare o molho com molho de soja, gengibre e alho.",
			"Frite a couve-flor até ficar crocante.",
			"Misture a couve-flor frita no molho.",
			"Decore com cebolinha e sirva quente.",
		],
	},
	{
		id: "05",
		name: "Frango",
		image: require("../../assets/images/chicken.png"),
		rating: "2.2",
		ingredients: ["Peito de Frango", "Sal", "Pimenta-do-Reino", "Azeite"],
		time: "45 min",
		difficulty: "Médio",
		calories: "450 cal",
		color: "#8d4004",
		description:
			"Um prato suculento de frango temperado com sal e pimenta, selado com azeite e assado até o ponto perfeito.",
		steps: [
			"Pré-aqueça o forno na temperatura indicada.",
			"Tempere os peitos de frango com sal e pimenta.",
			"Aqueça o azeite em uma frigideira.",
			"Doure os dois lados do frango.",
			"Transfira para o forno e asse até cozinhar completamente.",
			"Sirva quente e aproveite!",
		],
	},
	{
		id: "06",
		name: "Cupcakes",
		image: require("../../assets/images/cupcakes.png"),
		rating: "5.0",
		ingredients: ["Farinha", "Açúcar", "Ovos", "Manteiga"],
		time: "60 min",
		difficulty: "Médio",
		calories: "200 cal",
		description:
			"Cupcakes deliciosos feitos com uma mistura perfeita de farinha, açúcar, ovos e manteiga — perfeitos para qualquer ocasião.",
		steps: [
			"Pré-aqueça o forno na temperatura indicada.",
			"Prepare a massa misturando todos os ingredientes.",
			"Coloque forminhas em uma assadeira para cupcakes.",
			"Preencha com a massa e leve ao forno.",
			"Deixe esfriar e decore como desejar.",
			"Desfrute dessas delícias doces!",
		],
	},
	{
		id: "07",
		name: "Curry",
		image: require("../../assets/images/curry.png"),
		rating: "4.8",
		ingredients: ["Carne", "Curry em Pó", "Leite de Coco", "Especiarias"],
		time: "55 min",
		difficulty: "Difícil",
		calories: "550 cal",
		color: "#d35400",
		description:
			"Um curry rico e aromático com pedaços macios de carne cozidos em uma mistura saborosa de curry em pó, leite de coco e especiarias.",
		steps: [
			"Tempere a carne com especiarias e deixe marinar.",
			"Aqueça óleo em uma panela grande e doure a carne.",
			"Adicione o curry em pó e misture bem.",
			"Acrescente o leite de coco e deixe ferver.",
			"Cozinhe em fogo baixo até a carne ficar macia.",
			"Sirva com arroz ou pão e aproveite!",
		],
	},
	{
		id: "08",
		name: "Ramen",
		image: require("../../assets/images/ramen-org.png"),
		rating: "4.2",
		ingredients: ["Macarrão Ramen", "Molho de Soja", "Ovos", "Vegetais"],
		time: "35 min",
		difficulty: "Fácil",
		calories: "400 cal",
		color: "#f96163",
		description:
			"Uma tigela reconfortante de ramen com macarrão delicioso, caldo à base de molho de soja, vegetais macios e ovos cozidos no ponto certo.",
		steps: [
			"Cozinhe o macarrão conforme as instruções da embalagem.",
			"Em uma panela, ferva água e adicione molho de soja.",
			"Adicione os vegetais picados e cozinhe até ficarem macios.",
			"Cozinhe os ovos e corte-os ao meio.",
			"Monte as tigelas com macarrão, vegetais e ovos.",
			"Despeje o caldo quente por cima e aproveite seu ramen caseiro!",
		],
	},
];
